###Signup
POST http://localhost:3000/api/users/signup
content-type: application/json

{
  "username": "test",
  "password": "test"
}

### Login
POST http://localhost:3000/api/users/login
content-type: application/json

{
  "username": "test",
  "password": "test"
}

### Get task
GET http://localhost:3000/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWI5ZjgzMzNiZWMzMmEzMjRlYmIyYjUiLCJpYXQiOjE2Mzk1NzgzOTYsImV4cCI6MTY0MjE3MDM5Nn0.kdtR86T443IgW51eI8gZBszZyNRb3CkcSR0slqRFjIs

### Create new Task
POST http://localhost:3000/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWI5ZjgzMzNiZWMzMmEzMjRlYmIyYjUiLCJpYXQiOjE2Mzk1NzgzOTYsImV4cCI6MTY0MjE3MDM5Nn0.kdtR86T443IgW51eI8gZBszZyNRb3CkcSR0slqRFjIs
content-type: application/json
 
 {
  "title": "Third task",
  "detail": "Hello world"
 }

### Edit a task
PATCH http://localhost:3000/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWI5ZjgzMzNiZWMzMmEzMjRlYmIyYjUiLCJpYXQiOjE2Mzk1NzgzOTYsImV4cCI6MTY0MjE3MDM5Nn0.kdtR86T443IgW51eI8gZBszZyNRb3CkcSR0slqRFjIs
content-type: application/json
 
{
  "id": "61ba0774e6d31e6a6cc7bc81",
  "title": "Editted task",
  "detail": "Hello world",
  "state": "1"
}

### Delete task
DELETE  http://localhost:3000/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWI5ZjgzMzNiZWMzMmEzMjRlYmIyYjUiLCJpYXQiOjE2Mzk1NzgzOTYsImV4cCI6MTY0MjE3MDM5Nn0.kdtR86T443IgW51eI8gZBszZyNRb3CkcSR0slqRFjIs
content-type: application/json
 
{
  "id": "61ba0a128e409cccbb8018c2"
}